<a href="https://colab.research.google.com/github/SupunGurusinghe/sqlite-plus-colab/blob/main/sg_project1_multivariate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Multivariate**

In [45]:
import pandas as pd

url1 = "https://raw.githubusercontent.com/SupunGurusinghe/sqlite-plus-colab/main/superstore_data.csv"
superstore_df1 = pd.read_csv(url1 ,encoding='windows-1252')

url2 = "https://raw.githubusercontent.com/SupunGurusinghe/sqlite-plus-colab/main/superstore.csv"
superstore_df2 = pd.read_csv(url2 ,encoding='windows-1252')

In [46]:
import sqlite3

conn = sqlite3.connect('test_database')
c = conn.cursor()

# dropping an existing table
c.execute("DROP TABLE IF EXISTS storefront1")

c.execute('''CREATE TABLE storefront1 (
  RowID INT, 
  OrderID VARCHAR(30),
  OrderDate VARCHAR(12),
  ShipDate VARCHAR(12),
  ShipMode VARCHAR(15),
  CustomerID VARCHAR(20),
  CustomerName VARCHAR(50),
  Segment VARCHAR(20),
  Country VARCHAR(20),
  City VARCHAR(20),
  State VARCHAR(20),
  PostalCode VARCHAR(15),
  Region VARCHAR(20),
  ProductID VARCHAR(30),
  Category VARCHAR(20),
  SubCategory VARCHAR(20),
  ProductName VARCHAR(20),
  Sales DOUBLE,
  Quantity INT,
  Discount DOUBLE,
  Profit DOUBLE)
''')

conn.commit()

superstore_df1.to_sql('storefront1', conn, if_exists='replace', index = False)
 
c.execute('''  
SELECT * FROM storefront1
          ''')

results = c.fetchall()
c.close()

df1 = pd.DataFrame(results, columns= ['RowID', 'OrderID', 'OrderDate', 'ShipDate', 'ShipMode', 'CustomerID', 'CustomerName', 'Segment', 'Country', 'City', 'State', 'PostalCode', 'Region', 'ProductID', 'Category', 'SubCategory', 'ProductName', 'Sales', 'Quantity', 'Discount', 'Profit'])
df1.head()

,RowID,OrderID,OrderDate,ShipDate,ShipMode,CustomerID,CustomerName,Segment,Country,City,...,PostalCode,Region,ProductID,Category,SubCategory,ProductName,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,None,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Suplease,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [47]:
conn = sqlite3.connect('test_database')
c = conn.cursor()

# dropping an existing table
c.execute("DROP TABLE IF EXISTS storefront2")

c.execute('''CREATE TABLE storefront2 (
  RowID INT, 
  OrderID VARCHAR(30),
  OrderDate VARCHAR(12),
  ShipDate VARCHAR(12),
  ShipMode VARCHAR(15),
  CustomerID VARCHAR(20),
  CustomerName VARCHAR(50),
  Segment VARCHAR(20),
  Country VARCHAR(20),
  City VARCHAR(20),
  State VARCHAR(20),
  PostalCode VARCHAR(15),
  Region VARCHAR(20),
  ProductID VARCHAR(30),
  Category VARCHAR(20),
  SubCategory VARCHAR(20),
  ProductName VARCHAR(20),
  Sales DOUBLE,
  Quantity INT,
  Discount DOUBLE,
  Profit DOUBLE)
''')

conn.commit()

superstore_df2.to_sql('storefront2', conn, if_exists='replace', index = False)
 
c.execute('''  
SELECT * FROM storefront2
          ''')

results = c.fetchall()
c.close()

df2 = pd.DataFrame(results, columns= ['RowID', 'OrderID', 'OrderDate', 'ShipDate', 'ShipMode', 'CustomerID', 'CustomerName', 'Segment', 'Country', 'City', 'State', 'PostalCode', 'Region', 'ProductID', 'Category', 'SubCategory', 'ProductName', 'Sales', 'Quantity', 'Discount', 'Profit'])
df2.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:2882: UserWarning:

The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.

,RowID,OrderID,OrderDate,ShipDate,ShipMode,CustomerID,CustomerName,Segment,Country,City,...,PostalCode,Region,ProductID,Category,SubCategory,ProductName,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [48]:
c.close()

In [49]:
c = conn.cursor()

def null_count(table_n):

  table_name = table_n

  c.execute("SELECT name FROM pragma_table_info(?) ORDER BY cid", [table_name])
  names = c.fetchall()

  result_list = []
  for name in names:
    result_list.append(name[0])

  c.execute(f'SELECT * FROM {table_name}')
  results = c.fetchall()

  df = pd.DataFrame(results, columns= result_list)
  df.head()

  null_count_matrix = []
  i = 0
  for col in df.columns:
    null_count_matrix.append([])

    null_count_matrix[i].append(col)
    null_count_matrix[i].append(df[col].isna().sum())
    null_count_matrix[i].append(df[df[col].isnull()].index.tolist())
    i += 1

  null_df = pd.DataFrame(null_count_matrix, columns= ['Column', 'NullCount', 'NullIdList'])

  return null_df

c.close()

In [50]:
c = conn.cursor()

null_df = null_count('storefront1')

c.close()

In [51]:
null_df

          Column  NullCount            NullIdList
0          RowID          0                    []
1        OrderID          0                    []
2      OrderDate          0                    []
3       ShipDate          0                    []
4       ShipMode          0                    []
5     CustomerID          0                    []
6   CustomerName          4       [8, 30, 52, 59]
7        Segment          0                    []
8        Country          0                    []
9           City          0                    []
10         State          0                    []
11    PostalCode          0                    []
12        Region          0                    []
13     ProductID          0                    []
14      Category          5  [0, 16, 54, 68, 111]
15   SubCategory          0                    []
16   ProductName          0                    []
17         Sales          0                    []
18      Quantity          0                    []
19      Discount          0                    []
20        Profit          0                    []

In [71]:
c = conn.cursor()

import plotly.express as px

def multivariate(table1, table2, df, df1):
  # get to a dataframe
  table1_output = null_df = null_count(table1)
  table2_output = null_df = null_count(table2)

  print("Dataframe 1 -- \n")
  print(df)

  print("-"*5)
  print("Dataframe 2 -- \n")
  print(df1)

  print("-"*5)
  print("Dataframe difference -- \n")
  print(df.compare(df1))

  print("-"*5)
  print("Dataframe difference keeping equal values -- \n")
  print(df.compare(df1, keep_equal=True))

  print("-"*5)
  print("Dataframe difference keeping same shape -- \n")
  print(df.compare(df1, keep_shape=True))
  
  print("-"*5)
  print("Dataframe difference keeping same shape and equal values -- \n")
  print(df.compare(df1, keep_shape=True, keep_equal=True))


  
  # compare null by ploting
  fig1 = px.bar(table1_output, 
                x='Column', 
                y='NullCount', 
                height=400, 
                title='Before')
  fig1.show()

  fig2 = px.bar(table2_output, 
                x='Column', 
                y='NullCount', 
                height=400, 
                title='After')
  fig2.show()

c.close()

In [72]:
c = conn.cursor()

multivariate('storefront1', 'storefront2', df1, df2)

c.close()

Dataframe 1 --

      RowID         OrderID   OrderDate    ShipDate        ShipMode  \
0         1  CA-2016-152156   11/8/2016  11/11/2016    Second Class
1         2  CA-2016-152156   11/8/2016  11/11/2016    Second Class
2         3  CA-2016-138688   6/12/2016   6/16/2016    Second Class
3         4  US-2015-108966  10/11/2015  10/18/2015  Standard Class
4         5  US-2015-108966  10/11/2015  10/18/2015  Standard Class
...     ...             ...         ...         ...             ...
9989   9990  CA-2014-110422   1/21/2014   1/23/2014    Second Class
9990   9991  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9991   9992  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9992   9993  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9993   9994  CA-2017-119914    5/4/2017    5/9/2017    Second Class

     CustomerID      CustomerName    Segment        Country             City  \
0      CG-12520       Claire Gute   Consumer  United States        Henderson
1      CG-12520       Claire Gute   Consumer  United States        Henderson
2      DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3      SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4      SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...         ...               ...        ...            ...              ...
9989   TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990   DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991   DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992   DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993   CC-12220      Chris Cortes   Consumer  United States      Westminster

      ... PostalCode  Region        ProductID         Category  SubCategory  \
0     ...      42420   South  FUR-BO-10001798             None    Bookcases
1     ...      42420   South  FUR-CH-10000454        Furniture       Chairs
2     ...      90036    West  OFF-LA-10000240  Office Supplies       Labels
3     ...      33311   South  FUR-TA-10000577        Furniture       Tables
4     ...      33311   South  OFF-ST-10000760  Office Suplease      Storage
...   ...        ...     ...              ...              ...          ...
9989  ...      33180   South  FUR-FU-10001889        Furniture  Furnishings
9990  ...      92627    West  FUR-FU-10000747        Furniture  Furnishings
9991  ...      92627    West  TEC-PH-10003645       Technology       Phones
9992  ...      92627    West  OFF-PA-10004041  Office Supplies        Paper
9993  ...      92683    West  OFF-AP-10002684  Office Supplies   Appliances

                                            ProductName     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2     Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                        Eldon Fold 'N Roll Cart System   22.3680         2
...                                                 ...       ...       ...
9989                             Ultra Door Pull Handle   25.2480         3
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2
9991                              Aastra 57i VoIP phone  258.5760         2
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 21 columns]
-----
Dataframe 2 --

      RowID         OrderID   OrderDate    ShipDate        ShipMode  \
0         1  CA-2016-152156   11/8/2016  11/11/2016    Second Class
1         2  CA-2016-152156   11/8/2016  11/11/2016    Second Class
2         3  CA-2016-138688   6/12/2016   6/16/2016    Second Class
3         4  US-2015-108966  10/11/2015  10/18/2015  Standard Class
4         5  US-2015-108966  10/11/2015  10/18/2015  Standard Class
...     ...             ...         ...         ...             ...
9989   9990  CA-2014-110422   1/21/2014   1/23/2014    Second Class
9990   9991  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9991   9992  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9992   9993  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9993   9994  CA-2017-119914    5/4/2017    5/9/2017    Second Class

     CustomerID      CustomerName    Segment        Country             City  \
0      CG-12520       Claire Gute   Consumer  United States        Henderson
1      CG-12520       Claire Gute   Consumer  United States        Henderson
2      DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3      SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4      SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...         ...               ...        ...            ...              ...
9989   TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990   DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991   DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992   DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993   CC-12220      Chris Cortes   Consumer  United States      Westminster

      ... PostalCode  Region        ProductID         Category  SubCategory  \
0     ...      42420   South  FUR-BO-10001798        Furniture    Bookcases
1     ...      42420   South  FUR-CH-10000454        Furniture       Chairs
2     ...      90036    West  OFF-LA-10000240  Office Supplies       Labels
3     ...      33311   South  FUR-TA-10000577        Furniture       Tables
4     ...      33311   South  OFF-ST-10000760  Office Supplies      Storage
...   ...        ...     ...              ...              ...          ...
9989  ...      33180   South  FUR-FU-10001889        Furniture  Furnishings
9990  ...      92627    West  FUR-FU-10000747        Furniture  Furnishings
9991  ...      92627    West  TEC-PH-10003645       Technology       Phones
9992  ...      92627    West  OFF-PA-10004041  Office Supplies        Paper
9993  ...      92683    West  OFF-AP-10002684  Office Supplies   Appliances

                                            ProductName     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2     Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                        Eldon Fold 'N Roll Cart System   22.3680         2
...                                                 ...       ...       ...
9989                             Ultra Door Pull Handle   25.2480         3
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2
9991                              Aastra 57i VoIP phone  258.5760         2
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 21 columns]
-----
Dataframe difference --

             OrderID                  OrderDate              ShipDate  \
                self           other       self      other       self
0                NaN             NaN        NaN        NaN        NaN
4                NaN             NaN        NaN        NaN        NaN
8                NaN             NaN        NaN        NaN        NaN
16               NaN             NaN        NaN        NaN        NaN
25               NaN             NaN        NaN        NaN        NaN
30               NaN             NaN        NaN        NaN        NaN
50    CA-2016-121755  CA-2015-115742  1/16/2016  4/18/2015  1/20/2016
52               NaN             NaN        NaN        NaN        NaN
54               NaN             NaN        NaN        NaN        NaN
59               NaN             NaN        NaN        NaN        NaN
64               NaN             NaN        NaN        NaN        NaN
68               NaN             NaN        NaN        NaN        NaN
111              NaN             NaN        NaN        NaN        NaN
357              NaN             NaN        NaN        NaN        NaN
695   CA-2017-156951  CA-2015-119291  10/1/2017  5/14/2015  10/8/2017
876   CA-2017-126074  CA-2016-116736  10/2/2017  1/17/2016  10/6/2017
1173             NaN             NaN        NaN        NaN        NaN
1271             NaN             NaN        NaN        NaN        NaN
1284             NaN             NaN        NaN        NaN        NaN
1332             NaN             NaN        NaN        NaN        NaN
1513             NaN             NaN        NaN        NaN        NaN
1770             NaN             NaN        NaN        NaN        NaN
1818             NaN             NaN        NaN        NaN        NaN
1820             NaN             NaN        NaN        NaN        NaN
1857             NaN             NaN        NaN        NaN        NaN
1943             NaN             NaN        NaN        NaN        NaN
1972             NaN             NaN        NaN        NaN        NaN
1995             NaN             NaN        NaN        NaN        NaN
2004             NaN             NaN        NaN        NaN        NaN
2106             NaN             NaN        NaN        NaN        NaN
2137             NaN             NaN        NaN        NaN        NaN
2159             NaN             NaN        NaN        NaN        NaN
2167             NaN             NaN        NaN        NaN        NaN
5220  CA-2017-145653  CA-2014-140487   9/1/2017  6/14/2014   9/1/2017
5957             NaN             NaN        NaN        NaN        NaN
8233             NaN             NaN        NaN        NaN        NaN
8416             NaN             NaN        NaN        NaN        NaN

                       ShipMode                 CustomerID            ...  \
          other            self           other       self     other  ...
0           NaN             NaN             NaN        NaN       NaN  ...
4           NaN             NaN             NaN        NaN       NaN  ...
8           NaN             NaN             NaN        NaN       NaN  ...
16          NaN             NaN             NaN        NaN       NaN  ...
25          NaN             NaN             NaN        NaN       NaN  ...
30          NaN             NaN             NaN        NaN       NaN  ...
50    4/22/2015    Second Class  Standard Class   EH-13945  DP-13000  ...
52          NaN             NaN             NaN        NaN       NaN  ...
54          NaN             NaN             NaN        NaN       NaN  ...
59          NaN             NaN             NaN        NaN       NaN  ...
64          NaN             NaN             NaN        NaN       NaN  ...
68          NaN             NaN             NaN        NaN       NaN  ...
111         NaN             NaN             NaN        NaN       NaN  ...
357         NaN             NaN             NaN        NaN       NaN  ...
695   5/17/2015  Standard Class     First Class   EB-13840  JO-15550  ...
876   1/21/2016             NaN             NaN   RF-19735  CC-12430  ...
1173        NaN             NaN             NaN        NaN       NaN  ...
1271        NaN             NaN             NaN        NaN       NaN  ...
1284        NaN             NaN             NaN        NaN       NaN  ...
1332        NaN             NaN             NaN        NaN       NaN  ...
1513        NaN             NaN             NaN        NaN       NaN  ...
1770        NaN             NaN             NaN        NaN       NaN  ...
1818        NaN             NaN             NaN        NaN       NaN  ...
1820        NaN             NaN             NaN        NaN       NaN  ...
1857        NaN             NaN             NaN        NaN       NaN  ...
1943        NaN             NaN             NaN        NaN       NaN  ...
1972        NaN             NaN             NaN        NaN       NaN  ...
1995        NaN             NaN             NaN        NaN       NaN  ...
2004        NaN             NaN             NaN        NaN       NaN  ...
2106        NaN             NaN             NaN        NaN       NaN  ...
2137        NaN             NaN             NaN        NaN       NaN  ...
2159        NaN             NaN             NaN        NaN       NaN  ...
2167        NaN             NaN             NaN        NaN       NaN  ...
5220  6/20/2014        Same Day  Standard Class   CA-12775  SR-20425  ...
5957        NaN             NaN             NaN        NaN       NaN  ...
8233        NaN             NaN             NaN        NaN       NaN  ...
8416        NaN             NaN             NaN        NaN       NaN  ...

      SubCategory               \
             self        other
0             NaN          NaN
4             NaN          NaN
8             NaN          NaN
16            NaN          NaN
25            NaN          NaN
30            NaN          NaN
50    Accessories       Labels
52            NaN          NaN
54            NaN          NaN
59            NaN          NaN
64            NaN          NaN
68            NaN          NaN
111           NaN          NaN
357           NaN          NaN
695         Paper       Labels
876   Furnishings  Accessories
1173          NaN          NaN
1271          NaN          NaN
1284          NaN          NaN
1332          NaN          NaN
1513          NaN          NaN
1770          NaN          NaN
1818          NaN          NaN
1820          NaN          NaN
1857          NaN          NaN
1943          NaN          NaN
1972          NaN          NaN
1995          NaN          NaN
2004          NaN          NaN
2106          NaN          NaN
2137          NaN          NaN
2159          NaN          NaN
2167          NaN          NaN
5220       Chairs    Bookcases
5957          NaN          NaN
8233          NaN          NaN
8416          NaN          NaN

                                           ProductName  \
                                                  self
0                                                  NaN
4                                                  NaN
8                                                  NaN
16                                                 NaN
25                                                 NaN
30                                                 NaN
50    Imation 8GB Mini TravelDrive USB 2.0 Flash Drive
52                                                 NaN
54                                                 NaN
59                                                 NaN
64                                                 NaN
68                                                 NaN
111                                                NaN
357                                                NaN
695        Personal Creations Ink Jet Cards and Labels
876                         Nu-Dell Leatherette Frames
1173                                               NaN
1271                                               NaN
1284                                               NaN
1332                                               NaN
1513                                               NaN
1770                                               NaN
1818                                               NaN
1820                                               NaN
1857                                               NaN
1943                                               NaN
1972                                               NaN
1995                                               NaN
2004                                               NaN
2106                                               NaN
2137                                               NaN
2159                                               NaN
2167                                               NaN
5220    Harbour Creations 67200 Series Stacking Chairs
5957                                               NaN
8233                                               NaN
8416                                               NaN

                                                          Sales          \
                                                  other    self   other
0                                                   NaN     NaN     NaN
4                                                   NaN     NaN     NaN
8                                                   NaN     NaN     NaN
16                                                  NaN     NaN     NaN
25                                                  NaN     NaN     NaN
30                                                  NaN     NaN     NaN
50                                            Avery 485   90.57   75.18
52                                                  NaN     NaN     NaN
54                                                  NaN     NaN     NaN
59                                                  NaN     NaN     NaN
64                                                  NaN     NaN     NaN
68                                                  NaN     NaN     NaN
111                                                 NaN     NaN     NaN
357                                                 NaN     NaN     NaN
695                                           Avery 490   91.84   47.36
876   Logitech 910-002974 M325 Wireless Mouse for We...  157.74   29.99
1173                                                NaN     NaN     NaN
1271                                                NaN     NaN     NaN
1284                                                NaN     NaN     NaN
1332                                                NaN     NaN     NaN
1513                                                NaN     NaN     NaN
1770                                                NaN     NaN     NaN
1818                                                NaN     NaN     NaN
1820                                                NaN     NaN     NaN
1857                                                NaN     NaN     NaN
1943                                                NaN     NaN     NaN
1972                                                NaN     NaN     NaN
1995                                                NaN     NaN     NaN
2004                                                NaN     NaN     NaN
2106                                                NaN     NaN     NaN
2137                                                NaN     NaN     NaN
2159                                                NaN     NaN     NaN
2167                                                NaN     NaN     NaN
5220                          Hon Metal Bookcases, Gray  498.26  212.94
5957                                                NaN     NaN     NaN
8233                                                NaN     NaN     NaN
8416                                                NaN     NaN     NaN

     Discount          Profit
         self other      self    other
0         NaN   NaN       NaN      NaN
4         NaN   NaN       NaN      NaN
8         NaN   NaN       NaN      NaN
16        NaN   NaN       NaN      NaN
25        NaN   NaN       NaN      NaN
30        NaN   NaN       NaN      NaN

In [ ]:
df = table1_output
  df1 = table2_output
  print("Dataframe 1 -- \n")
  print(df)

  print("-"*5)
  print("Dataframe 2 -- \n")
  print(df1)

  print("-"*5)
  print("Dataframe difference -- \n")
  print(df.compare(df1))

  print("-"*5)
  print("Dataframe difference keeping equal values -- \n")
  print(df.compare(df1, keep_equal=True))

  print("-"*5)
  print("Dataframe difference keeping same shape -- \n")
  print(df.compare(df1, keep_shape=True))
  
  print("-"*5)
  print("Dataframe difference keeping same shape and equal values -- \n")
  print(df.compare(df1, keep_shape=True, keep_equal=True))